// Generated by https://quicktype.io

export interface StudentResponse {
    identification: string;
    name:           string;
    address:        string;
    phone:          string;
    _id:            string;
    __v:            number;
}
