// Generated by https://quicktype.io

export interface Book {
    _id:         string;
    isbn:        string;
    name:        string;
    edition:     string;
    observation: string;
    author:      Author;
    category:    Author;
    editorial:   Author;
    __v:         number;
}

export interface Author {
    _id:          string;
    __v:          number;
    gender?:      string;
    name:         string;
    description?: string;
}

export type BookPayload = Omit<Book, '_id' | '__v'>